version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend
    working_dir: /app/backend
    command: npm start
    ports:
      - '3001:3001'
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: .
      target: frontend
    working_dir: /app/frontend
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
